<a href="https://colab.research.google.com/github/friskyamirontoneng/Data-Mining/blob/main/My_Preprocessing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset=pd.read_csv('Data.csv')
X=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values

In [ ]:
print(X)

[['Matematika' 15.0 80.5]
 ['Fisika' 17.0 55.5]
 ['Kimia' 16.0 nan]
 ['Biologi' 18.0 80.7]
 ['Matematika' 17.0 70.5]
 ['Fisika' nan 85.2]
 ['Kimia' 15.0 87.2]
 ['Biologi' 16.0 80.5]
 ['Matematika' 17.0 75.7]
 ['Fisika' 18.0 85.9]]


In [ ]:
print(y)

[' Ya' ' Tidak' ' Tidak' ' Ya' ' Ya' ' Ya' ' Tidak' ' Tidak' ' Ya' ' Ya']


In [ ]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
print(X)

[['Matematika' 15.0 80.5]
 ['Fisika' 17.0 55.5]
 ['Kimia' 16.0 77.96666666666665]
 ['Biologi' 18.0 80.7]
 ['Matematika' 17.0 70.5]
 ['Fisika' 16.555555555555557 85.2]
 ['Kimia' 15.0 87.2]
 ['Biologi' 16.0 80.5]
 ['Matematika' 17.0 75.7]
 ['Fisika' 18.0 85.9]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[0.0 0.0 0.0 1.0 15.0 80.5]
 [0.0 1.0 0.0 0.0 17.0 55.5]
 [0.0 0.0 1.0 0.0 16.0 77.96666666666665]
 [1.0 0.0 0.0 0.0 18.0 80.7]
 [0.0 0.0 0.0 1.0 17.0 70.5]
 [0.0 1.0 0.0 0.0 16.555555555555557 85.2]
 [0.0 0.0 1.0 0.0 15.0 87.2]
 [1.0 0.0 0.0 0.0 16.0 80.5]
 [0.0 0.0 0.0 1.0 17.0 75.7]
 [0.0 1.0 0.0 0.0 18.0 85.9]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[1 0 0 1 1 1 0 0 1 1]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split( X, y, test_size=0.2, random_state=1 )

In [ ]:
print(X_train)

[[0.0 0.0 1.0 0.0 15.0 87.2]
 [0.0 0.0 0.0 1.0 17.0 70.5]
 [0.0 0.0 0.0 1.0 15.0 80.5]
 [1.0 0.0 0.0 0.0 18.0 80.7]
 [0.0 1.0 0.0 0.0 17.0 55.5]
 [1.0 0.0 0.0 0.0 16.0 80.5]
 [0.0 0.0 0.0 1.0 17.0 75.7]
 [0.0 1.0 0.0 0.0 16.555555555555557 85.2]]


In [ ]:
print(X_test)

[[0.0 0.0 1.0 0.0 16.0 77.96666666666665]
 [0.0 1.0 0.0 0.0 18.0 85.9]]


In [ ]:
print(y_train)

[0 1 1 1 0 0 1 1]


In [ ]:
print(y_test)

[0 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train [:, 3:]= sc.fit_transform(X_train[:, 3:])
X_test [:, 3:] = sc.transform(X_test[:, 3:])

In [ ]:
print(X_train)

[[0.0 0.0 1.0 -0.7745966692414834 -1.4696068892549743 1.0810765704617529]
 [0.0 0.0 0.0 1.2909944487358056 0.5652334189442231 -0.6845937206591554]
 [0.0 0.0 0.0 1.2909944487358056 -1.4696068892549743 0.37269387881444227]
 [1.0 0.0 0.0 -0.7745966692414834 1.5826535730438218 0.3938396308039145]
 [0.0 1.0 0.0 -0.7745966692414834 0.5652334189442231 -2.2705251198695517]
 [1.0 0.0 0.0 -0.7745966692414834 -0.4521867351553756 0.37269387881444227]
 [0.0 0.0 0.0 1.2909944487358056 0.5652334189442231 -0.1348041689328843]
 [0.0 1.0 0.0 -0.7745966692414834 0.11304668378884751 0.8696190505670335]]


In [ ]:
print(X_test)

[[0.0 0.0 1.0 -0.7745966692414834 -0.4521867351553756 0.10484768694779623]
 [0.0 1.0 0.0 -0.7745966692414834 1.5826535730438218 0.9436291825301856]]
